# Generated by Django 5.0.1 on 2024-01-23 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('company_or_institution', models.CharField(max_length=200, verbose_name='Company/Institution')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Department')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number')),
                ('contact_address', models.TextField(verbose_name='Contact Address')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('postcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='ZIP/Postcode')),
                ('country', models.CharField(max_length=200, verbose_name='country')),
                ('submitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
