# Generated by Django 5.0.1 on 2024-01-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
