# Generated by Django 5.0.1 on 2024-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_system', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='uidb64',
            field=models.TextField(unique=True, verbose_name='uidb64'),
        ),
    ]
