# Generated by Django 5.0.1 on 2024-01-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_system', '0004_alter_pendinguser_uidb64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='uidb64',
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='token',
            field=models.TextField(unique=True, verbose_name='token'),
        ),
    ]
